### PR TITLE
Merge Story 0 into master

### PR DESCRIPTION
**Pull request by deadlyfingers**
Update master with postcard app (story_0 branch)

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/postcardapp/63)

### CODE REVIEW

**Comment by yaronyg** [comment]
@deadlyfingers - There is a merge conflict. You need to resolve that first.

**Comment by yaronyg** [comment]
10/27 - Needs to resolve merge conflicts (it's a theme!)

**Comment by yaronyg** [comment]
10/28 - No work on this today because of the website work. BTW this is for #233

**Comment by deadlyfingers** [comment]
Using P4Merge for resolving conflicts but sometimes it joins left+right as one entity so you can't choose left or right separately... Any other merge tool suggestions?

**Comment by yaronyg** [comment]
10/30 - So yeah, there is a PR. Booo it still needs to have the merge conflict resolved.

**Pull request merged**
