### PR TITLE
Update the app based on install scipt

### PR DESCRIPTION
**Pull request by sreesharp**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/thaliproject/postcardapp/pull/15%23issuecomment-125785787%22%2C%20%22https%3A//github.com/thaliproject/postcardapp/pull/15%23issuecomment-131219627%22%2C%20%22https%3A//github.com/thaliproject/postcardapp/pull/15%23issuecomment-131237363%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/thaliproject/postcardapp/pull/15%23issuecomment-125785787%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ca%20href%3D%5C%22http%3A//app.review.ninja/thaliproject/postcardapp/pull/15%5C%22%20target%3D%5C%22_blank%5C%22%3E%3Cimg%20src%3D%5C%22http%3A//app.review.ninja/35637856/pull/15/badge%5C%22%20alt%3D%5C%22ReviewNinja%5C%22/%3E%22%2C%20%22created_at%22%3A%20%222015-07-29T00%3A04%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8714728%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/review-ninja%22%7D%7D%2C%20%7B%22body%22%3A%20%22This%20PR%20is%20no%20more%20relevant.%22%2C%20%22created_at%22%3A%20%222015-08-14T19%3A55%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5561852%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sreesharp%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%20for%20closing%20this%21%22%2C%20%22created_at%22%3A%20%222015-08-14T20%3A57%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1480964%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/yaronyg%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/thaliproject/postcardapp/pull/15#issuecomment-125785787'>General Comment</a></b>
- <a href='https://github.com/review-ninja'></a> <a href="http://app.review.ninja/thaliproject/postcardapp/pull/15" target="_blank">ReviewNinja
- <a href='https://github.com/sreesharp'></a> This PR is no more relevant.
- <a href='https://github.com/yaronyg'></a> Thanks for closing this!

<a href='https://www.codereviewhub.com/thaliproject/postcardapp/pull/15?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/thaliproject/postcardapp/pull/15?approve=1'></a>&nbsp;<a href='https://github.com/thaliproject/postcardapp/pull/15'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/thaliproject/postcardapp/pull/15" target="_blank">ReviewNinja

**Comment by yaronyg** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/thaliproject/postcardapp/pull/15'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by sreesharp** [comment]
This PR is no more relevant.

**Comment by yaronyg** [comment]
Thanks for closing this!

**Pull request closed without merging**
