### PR TITLE
Story 001 updates

### PR DESCRIPTION
**Pull request by deadlyfingers**
Updates:
- Thali Cordova plugin 2.1.0
- Cordova 6 supported
- Appium E2E UX tests

@yaronyg After merge should we take opportunity to clean branches and then switch to issue branching system?

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/postcardapp/129)

### CODE REVIEW

**Comment by mpodwysocki** [comment]
Review status: 0 of 110 files reviewed at latest revision, 8 unresolved discussions.

---

_[.gitignore, line 49 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBsy_kOBGowk0hQbNBC:-KBsy_kPfid-ILARtQNF:-330847314) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/.gitignore#L49)):_
I'd also add:

# Node

node_modules
npm-debug.log

# IDEs

.vscode
.idea

---

_[app/jxcore/app.js, line 2 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBsz4aCN0BlqDZpmUIH:-KBsz4aCN0BlqDZpmUII:710486685) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/app.js#L2)):_
What from ESNext are we using here?  And if so should it be in our regular .jshintrc file?

---

_[app/jxcore/hook.js, line 1 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBszilYfRZICR3YuJB3:-KBszilZwgG-W1Iex-01:571095901) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/hook.js#L1)):_
missing 'use strict'

---

_[app/jxcore/public/elements/routing.html, line 16 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt-PTqXHQo6TPKm5Q8:-KBt-PTrTmx_F-KyooMK:2045443729) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/public/elements/routing.html#L16)):_
That's a redundant check since myApp.username truthy check already checks for '' for example:

var foo = '';
if (foo) { console.log('hi'); /\* never runs */ }

---

_[app/jxcore/routes/_api.js, line 11 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt35rew73mTXQQHJkx:-KBt35rfLBVSfXNPyxGg:1261139080) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/routes/_api.js#L11)):_
Should there be null checks as well? You could do the same here with req.body.username == null which checks for null and undefined

---

_[app/jxcore/routes/_api.js, line 19 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt3Ge4FdL03qK5ATgO:-KBt3Ge4FdL03qK5ATgP:-1245404845) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/routes/_api.js#L19)):_
The lengths can't be less than zero

---

_[test/helpers/caps.js, line 1 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt41VMNRoSCh6T2u_j:-KBt41VNGVLJEYo_VLo4:-1728610629) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/test/helpers/caps.js#L1)):_
strict mode missing

---

_[test/helpers/setup.js, line 1 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt47gYVHfVXbmxPB7D:-KBt47gYVHfVXbmxPB7E:846425864) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/test/helpers/setup.js#L1)):_
missing strict

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/129)_

**Comment by mpodwysocki** [comment]
Reviewed 116 of 116 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/129)_

**Comment by deadlyfingers** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[app/jxcore/app.js, line 2 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBsz4aCN0BlqDZpmUIH:-KCuZgDlOkkmYGDX2Hmx:1763091608) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/app.js#L2)):_
I can only imagine I added this to mute some jshint warning, but will take it out as I don't see any warnings in Atom editor now.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/129)_

**Comment by deadlyfingers** [comment]
Review status: 93 of 110 files reviewed at latest revision, 8 unresolved discussions.

---

_[.gitignore, line 49 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBsy_kOBGowk0hQbNBC:-KCvAtSvUGWSieGs220U:-499146009) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/.gitignore#L49)):_
Done.

---

_[app/jxcore/app.js, line 2 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBsz4aCN0BlqDZpmUIH:-KCvAss5s5abkRWltCxI:-499146009) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/app.js#L2)):_
Done.

---

_[app/jxcore/hook.js, line 1 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBszilYfRZICR3YuJB3:-KCvAsFqT7dQLuleYe3T:-499146009) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/hook.js#L1)):_
Done.

---

_[app/jxcore/public/elements/routing.html, line 16 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt-PTqXHQo6TPKm5Q8:-KCvAqfnut7ff95JsAba:-499146009) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/public/elements/routing.html#L16)):_
Done.

---

_[app/jxcore/routes/_api.js, line 11 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt35rew73mTXQQHJkx:-KCvAushboi0qyaB75Tf:-499146009) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/routes/_api.js#L11)):_
Done.

---

_[app/jxcore/routes/_api.js, line 19 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt3Ge4FdL03qK5ATgO:-KCvAvSvORa8kOlO11Ky:-499146009) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/app/jxcore/routes/_api.js#L19)):_
Done.

---

_[test/helpers/caps.js, line 1 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt41VMNRoSCh6T2u_j:-KCvAww3vAa_JwIx3Mt9:-499146009) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/test/helpers/caps.js#L1)):_
Done.

---

_[test/helpers/setup.js, line 1 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/129#-KBt47gYVHfVXbmxPB7D:-KCvAxfjqNMxgdJYRi_r:-499146009) ([raw file](https://github.com/thaliproject/postcardapp/blob/299c38e5fc0f7c640e379f7686fcbd6bef0c3b2a/test/helpers/setup.js#L1)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/129)_

**Pull request merged**
