### PR TITLE
Story 0 dadougla

### PR DESCRIPTION
**Pull request by deadlyfingers**
Minor update to fix first run issues on Android and iOS for story_0

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/postcardapp/57)

### CODE REVIEW

**Comment by mpodwysocki** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[www/jxcore/app.js, line 23 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/57#-K19txbeOdue93HDURJh)** ([raw file](https://github.com/thaliproject/postcardapp/blob/d485db47d937ab0f32ce490141a13ec1b1328900/www/jxcore/app.js#L23)):</sup>
Instead of just logging it, shouldn't this be a fatal error and we just crash?



---

<sup>**[www/jxcore/cardroutes.js, line 11 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/57#-K19sobjE5Wt1LGqcpqX)** ([raw file](https://github.com/thaliproject/postcardapp/blob/d485db47d937ab0f32ce490141a13ec1b1328900/www/jxcore/cardroutes.js#L11)):</sup>
Instead, use res.status(400).json({ error: 'Username is undefined' })



---

<sup>**[www/jxcore/cardroutes.js, line 16 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/57#-K19tKa6HWiluHDF_bMa)** ([raw file](https://github.com/thaliproject/postcardapp/blob/d485db47d937ab0f32ce490141a13ec1b1328900/www/jxcore/cardroutes.js#L16)):</sup>
If you're already trimming above, why do it again?



---

<sup>**[www/jxcore/cardroutes.js, line 17 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/57#-K19tQUrCoMqnKNzPVZw)** ([raw file](https://github.com/thaliproject/postcardapp/blob/d485db47d937ab0f32ce490141a13ec1b1328900/www/jxcore/cardroutes.js#L17)):</sup>
Instead, use res.status(400).json({ error: 'Username is required' })



---

<sup>**[www/jxcore/package.json, line 11 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/57#-K19tXWQ4YjEx5MDo8kn)** ([raw file](https://github.com/thaliproject/postcardapp/blob/d485db47d937ab0f32ce490141a13ec1b1328900/www/jxcore/package.json#L11)):</sup>
why are we pegging it to a release instead of saying ^1.4.1 which says upwards of 1.4?



---

<sup>**[www/jxcore/package.json, line 13 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/57#-K19tcqMOG5_Xi5dqz_O)** ([raw file](https://github.com/thaliproject/postcardapp/blob/d485db47d937ab0f32ce490141a13ec1b1328900/www/jxcore/package.json#L13)):</sup>
Same applies to this, why are we pegged at only 5.0.0 instead of ^5.0.0 and upwards?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/57)

**Comment by deadlyfingers** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[www/jxcore/app.js, line 23 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/57#-K19txbeOdue93HDURJh)** ([raw file](https://github.com/thaliproject/postcardapp/blob/d485db47d937ab0f32ce490141a13ec1b1328900/www/jxcore/app.js#L23)):</sup>
It will fallback to use the 'dbPath' tmp directory... so it should continue to run albeit with temporary db 



---

<sup>**[www/jxcore/package.json, line 11 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/57#-K19tXWQ4YjEx5MDo8kn)** ([raw file](https://github.com/thaliproject/postcardapp/blob/d485db47d937ab0f32ce490141a13ec1b1328900/www/jxcore/package.json#L11)):</sup>
Ah this is to solve the leveldown bindings issue running on localhost - https://github.com/thaliproject/postcardapp/issues/50



---

<sup>**[www/jxcore/package.json, line 13 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/57#-K19tcqMOG5_Xi5dqz_O)** ([raw file](https://github.com/thaliproject/postcardapp/blob/d485db47d937ab0f32ce490141a13ec1b1328900/www/jxcore/package.json#L13)):</sup>
Linked to same leveldown issue - https://github.com/thaliproject/postcardapp/issues/50



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/57)

**Comment by mpodwysocki** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/57)

**Comment by mpodwysocki** [comment]
Reviewed 5 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/57)

**Pull request merged**
