### PR TITLE
Story 0 - Automatic refresh

### LINKED ISSUE #31: Remove refresh button
Changes should be automatically synced instead.

### LINKED ISSUE #45: Refresh only changes
Instead of automatically reloading postcard data when changes are detected we should use the event detail to reflect these changes on the client. Related to issue #31

### PR DESCRIPTION
**Pull request by deadlyfingers**
Updates only changes (delete, update or create) to close #45.
Removes reload button to close #31.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/postcardapp/46)

### CODE REVIEW

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/elements/page-editor/page-editor.html, line 128 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/46#-K-ZXq1XNO_yYW-WNZ4j)** ([raw file](https://github.com/thaliproject/postcardapp/blob/3eef53cd91020cf69225e43be0a4198014baabf8/www/jxcore/public/elements/page-editor/page-editor.html#L128)):</sup>
Is context really needed here?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/46)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/elements/page-home/page-home.html, line 132 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/46#-K-ZY5Op7rNJnOhhUGkf)** ([raw file](https://github.com/thaliproject/postcardapp/blob/3eef53cd91020cf69225e43be0a4198014baabf8/www/jxcore/public/elements/page-home/page-home.html#L132)):</sup>
Once again, is context needed?  We're not using it in any of our callbacks



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/46)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/elements/page-editor/page-editor.html, line 137 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/46#-K-Z_eAJsaa-c9myyZ_Z)** ([raw file](https://github.com/thaliproject/postcardapp/blob/3eef53cd91020cf69225e43be0a4198014baabf8/www/jxcore/public/elements/page-editor/page-editor.html#L137)):</sup>
Unless we're using any of the variables, it's not necessary to declare any of these variables



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/46)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/elements/page-editor/page-editor.html, line 139 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/46#-K-Z_liSXHJW-ueESOKQ)** ([raw file](https://github.com/thaliproject/postcardapp/blob/3eef53cd91020cf69225e43be0a4198014baabf8/www/jxcore/public/elements/page-editor/page-editor.html#L139)):</sup>
Unless we're using all of the variables such as textStatus and jqXHR, it's not necessary to declare them



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/46)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/elements/page-home/page-home.html, line 135 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/46#-K-Za9ZRFflyON1XB33x)** ([raw file](https://github.com/thaliproject/postcardapp/blob/3eef53cd91020cf69225e43be0a4198014baabf8/www/jxcore/public/elements/page-home/page-home.html#L135)):</sup>
Same applies here from above, if not using the variables, no bother to declare them



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/46)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/elements/page-home/page-home.html, line 137 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/46#-K-ZaEfoVQMAZBr6mmCk)** ([raw file](https://github.com/thaliproject/postcardapp/blob/3eef53cd91020cf69225e43be0a4198014baabf8/www/jxcore/public/elements/page-home/page-home.html#L137)):</sup>
Same comment as above, if not using textStatus and jqXHR, no need to declare them



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/46)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/elements/page-home/page-home.html, line 297 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/46#-K-Zaaf4xFGprrNFkt6L)** ([raw file](https://github.com/thaliproject/postcardapp/blob/3eef53cd91020cf69225e43be0a4198014baabf8/www/jxcore/public/elements/page-home/page-home.html#L297)):</sup>
same nitpick as above with unused variables



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/46)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/elements/page-home/page-home.html, line 300 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/46#-K-ZahMgkKEbwGK4FxyH)** ([raw file](https://github.com/thaliproject/postcardapp/blob/3eef53cd91020cf69225e43be0a4198014baabf8/www/jxcore/public/elements/page-home/page-home.html#L300)):</sup>
same nitpick as above with unused variables



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/46)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/elements/page-login/page-login.html, line 54 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/46#-K-ZbGA_Fx5ANZqwa8G3)** ([raw file](https://github.com/thaliproject/postcardapp/blob/3eef53cd91020cf69225e43be0a4198014baabf8/www/jxcore/public/elements/page-login/page-login.html#L54)):</sup>
Same nitpick as above



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/46)

**Comment by yaronyg** [comment]
David is just testing

**Comment by yaronyg** [comment]
Put in a description of how to fix the cordova plugin and release.

**Comment by yaronyg** [comment]
It seems to be working? He needs to run through the run through the readme.

**Comment by deadlyfingers** [comment]
Tested on iOS 8 devices - iPhone 5S and iPhone 6. Also works on iOS 9 with App Transport info.plist fix. 
Tested on Android L devices - Moto G (2nd Gen) with 5.0.2 and Xperia with 5.0.

**Pull request merged**
