### PR TITLE
Story 001 dadougla

### PR DESCRIPTION
**Pull request by deadlyfingers**
Identity Exchange using TRM

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/postcardapp/68)

### CODE REVIEW

**Comment by mpodwysocki** [comment]
<sup>**[cleanup.bat, line 3 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/68#-K2sl1xE3RvjV3ZocSdj)** ([raw file](https://github.com/thaliproject/postcardapp/blob/c6f18c2bf0f1f42e042bde52d4efe2e7ed2a8373/cleanup.bat#L3)):</sup>
There seems to be a weird space value there...



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/68)

**Comment by mpodwysocki** [comment]
<sup>**[readme.md, line 18 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/68#-K2sl9f62kNLm9Atb0zo)** ([raw file](https://github.com/thaliproject/postcardapp/blob/c6f18c2bf0f1f42e042bde52d4efe2e7ed2a8373/readme.md#L18)):</sup>
Is this still true?  For example, could we point them to use the VC++ Build Tools Preview? https://www.microsoft.com/en-us/download/details.aspx?id=49512



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/68)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/routes/manager.js, line 8 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/68#-K2smjkD8TMq0Yfxp4M9)** ([raw file](https://github.com/thaliproject/postcardapp/blob/c6f18c2bf0f1f42e042bde52d4efe2e7ed2a8373/www/jxcore/routes/manager.js#L8)):</sup>
you should wait for the started before sending a 200



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/68)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/routes/manager.js, line 14 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/68#-K2smox-mgE0wTwjkcFB)** ([raw file](https://github.com/thaliproject/postcardapp/blob/c6f18c2bf0f1f42e042bde52d4efe2e7ed2a8373/www/jxcore/routes/manager.js#L14)):</sup>
Likewise, you might want to wait for a full stop before sending a 200



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/68)

**Comment by mpodwysocki** [comment]
<sup>**[readme.md, line 15 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/68#-K2wP6uCi4snysXUHqdO)** ([raw file](https://github.com/thaliproject/postcardapp/blob/7e0d221edc94f1a949ab15a46f8b095dd24ad08c/readme.md#L15)):</sup>
You should also note that it comes directly with Node.js so no need to download node-gyp itself



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/68)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/scripts/app.js, line 43 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/68#-K2wPqF1paXtK4sTbcOd)** ([raw file](https://github.com/thaliproject/postcardapp/blob/7e0d221edc94f1a949ab15a46f8b095dd24ad08c/www/jxcore/public/scripts/app.js#L43)):</sup>
Why would socket.io be unavailable?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/68)

**Comment by mpodwysocki** [comment]
<sup>**[www/jxcore/public/scripts/app.js, line 124 [r2]](https://reviewable.io:443/reviews/thaliproject/postcardapp/68#-K2wQ5-dlaSjEelq-sq2)** ([raw file](https://github.com/thaliproject/postcardapp/blob/7e0d221edc94f1a949ab15a46f8b095dd24ad08c/www/jxcore/public/scripts/app.js#L124)):</sup>
Much easier to say functionToCheck && Object.prototype.toString.call(functionToCheck) === '[object Function]';



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/68)

**Comment by deadlyfingers** [comment]
Review status: 0 of 79 files reviewed at latest revision, 2 unresolved discussions.

---

_[cleanup.bat, line 3 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/68#-K2sl1xE3RvjV3ZocSdj:-K3VTQ6nWtBIC6Dmabyn:-1731494030) ([raw file](https://github.com/thaliproject/postcardapp/blob/c6f18c2bf0f1f42e042bde52d4efe2e7ed2a8373/cleanup.bat#L3)):_
Arg a gremlin! I think this entire file can be ditched now though.

---

_[readme.md, line 18 [r1]](https://reviewable.io:443/reviews/thaliproject/postcardapp/68#-K2sl9f62kNLm9Atb0zo:-K3VUZmoz7q3FFcq0Sns:682242726) ([raw file](https://github.com/thaliproject/postcardapp/blob/c6f18c2bf0f1f42e042bde52d4efe2e7ed2a8373/readme.md#L18)):_
Ok I would need to test that. We should prob create an issue for doing a Windows setup readme.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/postcardapp/68)_

**Pull request merged**
